A = int(input("Enter the first number: "))
B = int(input("Enter the second number: "))
Addition = (A+B)
print("Addition:", Addition)
Substraction = (A-B)
print("Substraction:", Substraction)
Multiplication = (A*B)
print("Multiplication:", Multiplication)
Division = (A/B)
print("Division:", Division)